### ISSUE TITLE
Docker build fails on Linux

### ISSUE THREAD

**Issue by kaibrooks** [GaloisInc/RustyFlight#2]
### Issue
Docker build fails in Ubuntu 18.04 with the following error:

<pre><code>
Compiling opener v0.4.1
error[E0432]: unresolved imports `syntax::token`, `syntax::token`
 --> /home/rustyflight/.cargo/registry/src/github.com-1ecc6299db9ec823/c2rust-ast-builder-0.14.0/src/builder.rs:8:21
  |
8 | use syntax::token::{self, TokenKind, Token};
  |             ^^^^^   ^^^^ no `token` in the root
  |             |
  |             could not find `token` in `syntax`
</pre></code>

Error persists like the above for 50 more compiles and then:

<pre><code>
error: aborting due to 50 previous errors

Some errors have detailed explanations: E0061, E0308, E0412, E0422, E0432, E0433, E0560.
For more information about an error, try `rustc --explain E0061`.
error: could not compile `c2rust-ast-builder`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `c2rust v0.14.0`, intermediate artifacts can be found at `/tmp/cargo-installjGhAgf`

Caused by:
  build failed
</pre></code>

### Hypothesis
I think this is due to the c2rust version? Maybe adjusting Dockerfile fixes it?

### Workaround
Build works under macOS 10.15.2, I built the container and then pushed it to the Docker Hub:

<pre><code>docker pull kaibrooks/rustyflight:latest</code></pre>

Not sure if this will introduce any unknown problems later, but it's been tested to work on Ubuntu 18.04

**Comment by acw** [comment]
Yeah, looks like `c2rust` updated. I'm testing a `Dockerfile` fix that will hopefully address this as we speak, and possibly serve as an example of how to track their development better.
